# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_AUTHORITY:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]

        in_memory:
            memory:
                users:
#                    admin:
#                        password: admin
#                        roles: 'ROLE_ADMIN'

        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            simple_preauth:
                authenticator: app.token_user_authenticator

        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
                csrf_provider: form.csrf_provider
                default_target_path: /
            logout:
                path:   /logout
                target: /login
            anonymous:    true

            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # profiling and other dev tools
        - { path: ^/(_(profiler|wdt)|css|images|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Basic user ACL
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/api/v\d+/login(?:\/)?$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/api/v\d+/logout(?:\/)?$, role: IS_AUTHENTICATED_ANONYMOUSLY }


        - { path: ^/api/user, role: [ROLE_USER, ROLE_AUTHORITY] }
        - { path: ^/blog, role: [ROLE_ADMIN, ROLE_AUTHORITY] }
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_AUTHORITY] }
        - { path: ^/authority, role: ROLE_AUTHORITY }
